### ISSUE TITLE
How does CRASHPlayer work?

### ISSUE THREAD

**Issue by commadelimited** [crashbob/CRASHPlayer#6]
I'm interested in trying this project out, perhaps even contributing to it. There doesn't appear to be any installation instructions though. How do I get it onto my Vizio M422I-B1? I see that it's JavaScript but does it compile? Can I add it to my TV via USB?

**Comment by rioniac** [comment]
The installation instructions can be found [here](https://github.com/crashbob/CRASHPlayer/blob/master/INSTALL).  
Just a warning: they are extensive, and may take some time.  
BUT it is TOTALLY worth it.  Although if you have a newer Vizio (not sure based on your model number), there may be a Plex app in your app store since it appears that your tv has "Vizio Internet Apps Plus."  
(whereas older tv's with just "Vizio Internet Apps" needed this extra addon)

**Comment by QuinDennis** [comment]
I've used the app for a couple of years, but recently it stopped working, it gets stuck at "loading".  I just got the latest copy, it behaves the same.  Vizio E320i-A0 ... (just this morning there was a store update, but CrashPlayer still won't load)
